name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 22.x
        uses: actions/setup-node@v1.4.4
        with:
          node-version: 22.x
      - name: Install Dependencies
        run: npm install
      - name: Start Tests
        run: npm test